### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by mausch** [jprante/elasticsearch-plugin-deploy#2]
Your plugin to install plugins on the fly looks amazing, thanks! Unfortunately I can't seem to get it to work.

When trying to install a plugin through `elasticsearch-plugin-deploy` on Windows, I don't get any errors when POSTing the zip address (a Windows file path) but apparently the plugin never gets loaded.

And when I try to restart Elasticsearch it won't start up, failing with this error:

```
[2015-01-09 14:41:06,088][INFO ][org.xbib.elasticsearch.module.deploy.DeployService] [Mister X] found plugin dir d:\servers\elasticsearch-1.4.2\plugins\deploy\plugins
[2015-01-09 14:41:06,089][INFO ][org.xbib.elasticsearch.module.deploy.DeployService] [Mister X] found plugin d:\servers\elasticsearch-1.4.2\plugins\deploy\plugins\myplugin
{1.4.2}: Startup Failed ...
- IllegalArgumentException[Illegal character in opaque part at index 7: file:d:\servers\elasticsearch-1.4.2\plugins\deploy\plugins\myplugin\elasticsearch-myplugin-1.0-SNAPSHOT.jar]
        URISyntaxException[Illegal character in opaque part at index 7: file:d:\servers\elasticsearch-1.4.2\plugins\deploy\plugins\myplugin\elasticsearch-myplugin-1.0-SNAPSHOT.jar]
Exception in thread "Thread-1" java.lang.NullPointerException
        at org.elasticsearch.cluster.action.index.MappingUpdatedAction.stop(MappingUpdatedAction.java:108)
        at org.elasticsearch.node.internal.InternalNode.stop(InternalNode.java:281)
        at org.elasticsearch.node.internal.InternalNode.close(InternalNode.java:320)
        at org.elasticsearch.bootstrap.Bootstrap$1.run(Bootstrap.java:75)
```

This `Illegal character in opaque part at index 7` seems to point to the colon from the Windows drive, which makes me think that somehow this doesn't support Windows.

Have you tried this on Windows? Is this a known issue? Any ideas of what might be causing this?

Thanks

**Comment by jprante** [comment]
The paths are processed as URLs. Please use '/' and not '\' in URLs.

**Comment by mausch** [comment]
Thanks. I am using '/'.. the `curl` command I use is:

```
$ curl -XPOST 'localhost:9200/_deploy' -d '{"name":"myplugin", "path": "d:/myplugin/target/releases/elasticsearch-myplugin-1.0-SNAPSHOT.zip"}'
```

The response from the server doesn't list any nodes:

`{"nodes":[],"deployed":true}`

But I see the following in the server log:

```
[2015-01-09 17:43:54,767][INFO ][org.xbib.elasticsearch.action.deploy.TransportDeployAction] [Marvel Girl] target is d:\servers\elasticsearch-1.4.2\plugins\deploy\plugins\myplugin\elasticsearch-myplugin-1.0-SNAPSHOT.zip
[2015-01-09 17:43:54,771][INFO ][org.xbib.elasticsearch.action.deploy.TransportDeployAction] [Marvel Girl] received 2841294 bytes
```

which means that the server does find the file. And d:\servers\elasticsearch-1.4.2\plugins\deploy\plugins\myplugin has all the JARs in the plugin ZIP.

**Comment by jprante** [comment]
Can you see under `plugins/deploy/plugins/myplugin` if the zip is being unpacked?

**Comment by mausch** [comment]
Yep, the unzipped JAR files are there. The `DeployService` isn't logging anything though, so it seems as if the JARs are being silently discarded or somehow not readable. I'll try adding some more logging in `DeployService.add`
